import Navbar from '@/components/Navbar'
import Head  from 'next/head'

export default function Home() {
  return (
    <>
    <Head>
      <title>Ibrahim | Portfolio</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
    </Head>
    <main className='w-full h-screen font-bodyFont bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll'>
      <Navbar></Navbar>
    </main>
    </>
    
  )
}
