import LiftSide from '@/components/LiftSide'
import Navbar from '@/components/Navbar'
import RightSide from '@/components/RightSide'
import Head  from 'next/head'
import { motion } from 'framer-motion';
import Banner from '@/components/Banner'
import About from '@/components/About';
import Experience from '@/components/Experience';

export default function Home() {
  return (
    <>
    <Head>
      <title>Ibrahim | Portfolio</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
    </Head>
    <main className='w-full h-screen font-bodyFont bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll'>
      <Navbar></Navbar>
      <div className='w-full h-[88vh] xl:flex items-center gap-20 justify-between'>
      <motion.div 
       initial={{opacity: 0}}
       animate={{opacity: 1}}
       transition={{duration:1.5}}
      className='hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0'>
      <LiftSide></LiftSide>
      </motion.div>
      <div className='h-[88vh] w-full mx-auto p-4'>
      <Banner></Banner>
      <About></About>
      <Experience></Experience>
      {/* Project */}
      {/* Archive */}
      {/* Contact */}
      {/* Footer */}
      </div>
      <motion.div 
       initial={{opacity: 0}}
       animate={{opacity: 1}}
       transition={{duration:1.5}}
      className='hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0'>
      <RightSide></RightSide>
      </motion.div>
      </div>
    </main>
    </>
    
  )
}
