import LiftSide from '@/components/LiftSide'
import Navbar from '@/components/Navbar'
import Head  from 'next/head'

export default function Home() {
  return (
    <>
    <Head>
      <title>Ibrahim | Portfolio</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
    </Head>
    <main className='w-full h-screen font-bodyFont bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll'>
      <Navbar></Navbar>
      <div className='w-full h-[88vh] xl:flex items-center gap-20 justify-between'>
      <div>
      <LiftSide></LiftSide>
      </div>
      <div>

      </div>
      <div>

      </div>
      </div>
    </main>
    </>
    
  )
}
